#!/usr/bin/env python3
import json
import os
import sys
from collections import OrderedDict


# FIDL libs have some unlisted dependencies.
_FIDL_LIB_DEPS = [
  "fidl_cpp_wire",
  "fidl_cpp_base_v2",
  "fidl_cpp_v2",
  "fidl_cpp",
  "fidl_cpp_sync",
  "fidl",
  "fidl_cpp_natural_ostream",
]

_GENERATED_PREAMBLE_FORMAT = """# DO NOT EDIT! This file was generated by
# {local_path}.
# Any changes made to this file will be discarded.
# To use this SDK in Meson, place or symlink this directory under subprojects/
# and call subproject(...) in your meson.build, then use dependency('<name>').

project('fuchsia-sdk', ['c', 'cpp'],
  default_options: ['cpp_std=c++20']
)

fuchsia_sdk_dir = meson.current_source_dir()
run_command('mkdir', '-p', fuchsia_sdk_dir / 'gen', check: true)
fuchsia_sdk_gen_inc = include_directories('gen')
fuchsia_sdk_fidl_ostream_inc = include_directories('pkg/fidl_cpp_natural_ostream/include')

zircon_dep = declare_dependency(
  link_args: ['-lzircon'],
)
zircon = zircon_dep
meson.override_dependency('zircon', zircon_dep)

"""

_SPACES_PER_INDENT = 2


def SanitizeIdentifier(name):
  return name.replace('.', '_').replace('-', '_')


def SerializeListOfStrings(strings, indent_level=1, separator='\n', prefix="", suffix=""):
  if isinstance(strings, str):
    return prefix + strings + suffix
  else:
    return (separator + ' ' * (indent_level * _SPACES_PER_INDENT)).join(
        [prefix + s + suffix for s in strings])


# result is an ordereddict
def CreateListOfFidlFiles(key, all_atoms, result=None):
  if result is None:
    result = OrderedDict()
  for dep in all_atoms[key]['deps_keys']:
    if dep not in result and all_atoms[dep]['type'] == 'fidl_library':
      CreateListOfFidlFiles(dep, all_atoms, result)
      # in case this node has been already added as a transitive
      # dependency, we must keep it in the initial order
      if dep not in result:
        result[dep] = all_atoms[dep]['sources']
  return result


def ConvertFidlLibrary(json, all_atoms, env_vars):
  key = json["key"]
  var_name = SanitizeIdentifier(key)
  fidl_dirname = "zx" if key == "zx_fidl" else key
  json_dirname = json["name"].replace('.', '/')

  files = [
    "fidl.h",
    "common_types.cc",
    "natural_messaging.cc",
    "natural_ostream.cc",
    "natural_types.cc",
    "type_conversions.cc",
    "wire_messaging.cc",
    "wire_types.cc",
  ]
  if key == 'zx_fidl':
    files = [
      "fidl.h",
    ]

  output_files = ["{}_{}".format(key, f) for f in files]

  fidl_deps_list = []
  for fidls in list(CreateListOfFidlFiles(key, all_atoms).values()):
    fidl_deps_list.append('--files ' + ' '.join(['"$1"/' + f for f in fidls]))
  fidl_deps_str = ' '.join(fidl_deps_list)

  fidl_sources_str = ' '.join(['"$1"/' + s for s in json['sources']])

  copy_cmds = [
    'cp "$1/gen/fidl/{fidl_dirname}/cpp/{f}" "$2/{out_f}"'.format(
        fidl_dirname=fidl_dirname, f=f, out_f=out_f)
    for f, out_f in zip(files, output_files)
  ]

  cmd_parts = [
    '"$1/tools/x64/fidlc" --name {name} --available fuchsia:{api_version} --json "$1/gen/{json_dirname}/{name}.json" {fidl_deps} --files {fidl_sources}'.format(
        name=json['name'],
        api_version=env_vars['api_version'],
        json_dirname=json_dirname,
        fidl_deps=fidl_deps_str,
        fidl_sources=fidl_sources_str),
    '"$1/tools/x64/fidlgen_cpp" --json "$1/gen/{json_dirname}/{name}.json" --root "$1/gen"'.format(
        json_dirname=json_dirname, name=json['name']),
    '"$1/tools/x64/fidlgen_hlcpp" --json "$1/gen/{json_dirname}/{name}.json" --root "$1/gen"'.format(
        json_dirname=json_dirname, name=json['name']),
  ] + copy_cmds

  shell_cmd = ' && '.join(cmd_parts)

  all_deps = []
  for d in json['deps_keys'] + _FIDL_LIB_DEPS:
    if d not in all_deps:
      all_deps.append(d)
  deps_vars = [SanitizeIdentifier(d) + '_dep' for d in all_deps]

  if key == 'zx_fidl':
    return """
# FIDL library {name}
{var_name}_fidl = custom_target(
  '{key}_fidl',
  output: [
    {outputs}
  ],
  depend_files: files(
    {depend_files}
  ),
  command: [
    'sh', '-c',
    '{shell_cmd}',
    'sh', fuchsia_sdk_dir, '@OUTDIR@',
  ],
)
{var_name}_dep = declare_dependency(
  sources: [{var_name}_fidl[0]],
  compile_args: ['-ffuchsia-api-level={api_version}'],
  include_directories: [fuchsia_sdk_fidl_ostream_inc, fuchsia_sdk_gen_inc],
  dependencies: [
    {deps}
  ],
)
{var_name} = {var_name}_dep
meson.override_dependency('{key}', {var_name}_dep)
## -- end of FIDL library {name}
""".format(
        name=json['name'],
        key=key,
        var_name=var_name,
        outputs=SerializeListOfStrings(output_files, indent_level=2, prefix="'", suffix="',"),
        depend_files=SerializeListOfStrings(json['sources'], indent_level=2, prefix="'", suffix="',"),
        shell_cmd=shell_cmd,
        api_version=env_vars['api_version'],
        deps=SerializeListOfStrings(deps_vars, indent_level=2, suffix=","),
    )

  return """
# FIDL library {name}
{var_name}_fidl = custom_target(
  '{key}_fidl',
  output: [
    {outputs}
  ],
  depend_files: files(
    {depend_files}
  ),
  command: [
    'sh', '-c',
    '{shell_cmd}',
    'sh', fuchsia_sdk_dir, '@OUTDIR@',
  ],
)
lib_{var_name} = static_library(
  '{var_name}',
  {var_name}_fidl,
  pic: true,
  build_by_default: false,
  cpp_args: ['-ffuchsia-api-level={api_version}'],
  include_directories: [fuchsia_sdk_fidl_ostream_inc, fuchsia_sdk_gen_inc],
  dependencies: [
    {deps}
  ],
)
{var_name}_dep = declare_dependency(
  sources: [{var_name}_fidl[0]],
  link_with: lib_{var_name},
  compile_args: ['-ffuchsia-api-level={api_version}'],
  include_directories: [fuchsia_sdk_fidl_ostream_inc, fuchsia_sdk_gen_inc],
  dependencies: [
    {deps}
  ],
)
{var_name} = {var_name}_dep
meson.override_dependency('{key}', {var_name}_dep)
## -- end of FIDL library {name}
""".format(
      name=json['name'],
      key=key,
      var_name=var_name,
      outputs=SerializeListOfStrings(output_files, indent_level=2, prefix="'", suffix="',"),
      depend_files=SerializeListOfStrings(json['sources'], indent_level=2, prefix="'", suffix="',"),
      shell_cmd=shell_cmd,
      api_version=env_vars['api_version'],
      deps=SerializeListOfStrings(deps_vars, indent_level=2, suffix=","),
  )


def ConvertSysroot(json, env_vars):
  return """
fuchsia_sysroot = fuchsia_sdk_dir / '{root}'
""".format(root=json['versions'][env_vars["target_arch"]]['root'])


def ConvertCcLibraryWithSource(json, all_atoms, env_vars):
  key = json['key']
  var_name = SanitizeIdentifier(key)
  sources = [source for source in json['sources'] if not source.endswith('.h')]
  deps_vars = [SanitizeIdentifier(d) + '_dep' for d in json['deps_keys']]

  inc_arg = ""
  if json.get('headers') and json.get('include_dir'):
    inc_arg = "  include_directories: include_directories('{}'),\n".format(json['include_dir'])

  deps_arg = ""
  if deps_vars:
    deps_arg = """  dependencies: [
    {deps}
  ],
""".format(deps=SerializeListOfStrings(deps_vars, indent_level=2, suffix=","))

  return """
# CC library {name}
lib_{var_name} = static_library(
  '{var_name}',
  files(
    {sources}
  ),
  pic: true,
  build_by_default: false,
  c_args: ['-ffuchsia-api-level={api_level}'],
  cpp_args: ['-ffuchsia-api-level={api_level}'],
{inc_arg}{deps_arg})
{var_name}_dep = declare_dependency(
  link_with: lib_{var_name},
  compile_args: ['-ffuchsia-api-level={api_level}'],
{inc_arg}{deps_arg})
{var_name} = {var_name}_dep
meson.override_dependency('{key}', {var_name}_dep)
## -- end of CC library {name}
""".format(
      key=key,
      var_name=var_name,
      name=json['name'],
      api_level=env_vars["api_version"],
      sources=SerializeListOfStrings(sources, indent_level=2, prefix="'", suffix="',"),
      inc_arg=inc_arg,
      deps_arg=deps_arg,
  )


def ConvertCcLibraryWithoutSource(json, all_atoms, env_vars):
  key = json['key']
  var_name = SanitizeIdentifier(key)
  deps_vars = [SanitizeIdentifier(d) + '_dep' for d in json['deps_keys']]

  inc_arg = ""
  if json.get('headers') and json.get('include_dir'):
    inc_arg = "  include_directories: include_directories('{}'),\n".format(json['include_dir'])

  deps_arg = ""
  if deps_vars:
    deps_arg = """  dependencies: [
    {deps}
  ],
""".format(deps=SerializeListOfStrings(deps_vars, indent_level=2, suffix=","))

  return """
# CC interface library {name}
{var_name}_dep = declare_dependency(
  compile_args: ['-ffuchsia-api-level={api_level}'],
{inc_arg}{deps_arg})
{var_name} = {var_name}_dep
meson.override_dependency('{key}', {var_name}_dep)
## -- end of CC interface library {name}
""".format(
      key=key,
      var_name=var_name,
      name=json['name'],
      api_level=env_vars["api_version"],
      inc_arg=inc_arg,
      deps_arg=deps_arg,
  )


def ConvertCcLibrary(json, all_atoms, env_vars):
  for source in json['sources']:
    if not source.endswith('.h'):
      return ConvertCcLibraryWithSource(json, all_atoms, env_vars)
  return ConvertCcLibraryWithoutSource(json, all_atoms, env_vars)


def ConvertCcPrebuiltLibrary(json, all_atoms, env_vars):
  key = json['key']
  var_name = SanitizeIdentifier(key)
  # TODO: handle non-shared libraries (link) properly
  prebuilt = json['binaries'][env_vars["target_arch"]][
      'dist' if json['format'] == "shared" else 'link']
  deps_vars = [SanitizeIdentifier(d) + '_dep' for d in json['deps_keys']]

  inc_arg = ""
  if json.get('headers') and json.get('include_dir'):
    inc_arg = "  include_directories: include_directories('{}'),\n".format(json['include_dir'])

  deps_arg = ""
  if deps_vars:
    deps_arg = """  dependencies: [
    {deps}
  ],
""".format(deps=SerializeListOfStrings(deps_vars, indent_level=2, suffix=","))

  return """
# CC prebuilt library {name}
{var_name}_dep = declare_dependency(
  compile_args: ['-ffuchsia-api-level={api_level}'],
  link_args: [fuchsia_sdk_dir / '{prebuilt}'],
{inc_arg}{deps_arg})
{var_name} = {var_name}_dep
meson.override_dependency('{key}', {var_name}_dep)
# -- end of CC prebuilt library {name}
""".format(
      name=json['name'],
      key=key,
      var_name=var_name,
      api_level=env_vars["api_version"],
      prebuilt=prebuilt,
      inc_arg=inc_arg,
      deps_arg=deps_arg,
  )


def ConvertNoOp(json, all_atoms, env_vars=None):
  return ""


_CONVERSION_FUNCTION_MAP = {
  'fidl_library': ConvertFidlLibrary,
  'cc_source_library': ConvertCcLibrary,
  'cc_prebuilt_library': ConvertCcPrebuiltLibrary,
  'host_tool': ConvertNoOp,
  'image': ConvertNoOp,
  'loadable_module': ConvertNoOp,
  'sysroot': ConvertNoOp,  # handled separately
  'documentation': ConvertNoOp,
}


def TopologicalSortAtoms(all_atoms):
  visited = set()
  ordered_keys = []

  def visit(key):
    if key in visited or key not in all_atoms:
      return
    visited.add(key)
    atom = all_atoms[key]
    deps = list(atom['deps_keys'])
    if atom['type'] == 'fidl_library':
      for d in _FIDL_LIB_DEPS:
        if d not in deps:
          deps.append(d)
    for dep in deps:
      visit(dep)
    ordered_keys.append(key)

  for key in all_atoms:
    visit(key)

  return ordered_keys


def GenerateMeson(root_dir):
  toplevel_meta = json.load(open(os.path.join(root_dir, 'meta',
                                              'manifest.json')))
  meson_output_path = os.path.join(root_dir, 'meson.build')
  os.makedirs(os.path.join(root_dir, 'gen'), exist_ok=True)
  print(("Generating {}...".format(meson_output_path)))
  with open(meson_output_path, 'w') as buildfile:
    # Write the preamble
    buildfile.write(_GENERATED_PREAMBLE_FORMAT.format(
        local_path=os.path.relpath(__file__, root_dir),
        sdk_dir=root_dir,
        build_file=meson_output_path))

    # Iterate through the manifest, building the dependency graph.
    all_atoms = OrderedDict()
    env_vars = {
      "api_version": 0,
      # TODO: figure out how to handle both platforms
      #"target_arch": "arm64",
      "target_arch": "x64",
    }
    for next_part in toplevel_meta['parts']:
      parsed = json.load(open(os.path.join(root_dir, next_part['meta'])))

      if next_part['type'] == "version_history":
        for levels in parsed["data"]["api_levels"]:
          env_vars["api_version"] = max(env_vars["api_version"], int(levels))
        continue

      if next_part['type'] == 'sysroot':
        buildfile.write(ConvertSysroot(parsed, env_vars))
        continue

      if next_part['type'] not in ['fidl_library', 'cc_source_library', 'cc_prebuilt_library']:
        print(('Ignoring SDK artifact type %s in name=%s root=%s.' %
              (next_part['type'], next_part.get('name', "<None>"), next_part.get('root', "<None>"))))
        continue

      if parsed.get('type', '') == 'fidl_library' and parsed.get('name') == 'zx':
        key = 'zx_fidl'
      else:
        key = parsed.get('name')

      if key in all_atoms:
        print(("oops, key %s is duplicated in list of atoms" % key))

      parsed['key'] = key
      deps_keys = []

      if parsed.get('type', '') == 'fidl_library':
        fidl_deps = parsed.get('deps', [])
        lib_deps = []
      elif parsed.get('type', '') in ['cc_source_library', 'cc_prebuilt_library']:
        fidl_deps = parsed.get('fidl_deps', [])
        lib_deps = parsed.get('deps', [])
      else:
        fidl_deps = []
        lib_deps = []

      for dep in fidl_deps:
        fidl_key = 'zx_fidl' if dep == 'zx' else dep
        if fidl_key not in deps_keys:
          deps_keys.append(fidl_key)
      for fidl_bindings in parsed.get("fidl_binding_deps", []):
        for dep in fidl_bindings.get("deps", []):
          fidl_key = 'zx_fidl' if dep == 'zx' else dep
          if fidl_key not in deps_keys:
            deps_keys.append(fidl_key)

      for dep in lib_deps:
        if dep not in deps_keys:
          deps_keys.append(dep)

      parsed['deps_keys'] = deps_keys
      all_atoms[key] = parsed

    print("API VERSION:", env_vars["api_version"])

    # Meson requires dependencies to be defined before they are referenced.
    for key in TopologicalSortAtoms(all_atoms):
      next_part = all_atoms[key]
      if 'type' not in next_part:
        raise Exception("Couldn't find 'type' node in %s." % next_part['name'])
      convert_function = _CONVERSION_FUNCTION_MAP.get(next_part['type'])
      buildfile.write(convert_function(next_part, all_atoms, env_vars))

  print(("Generated {}".format(meson_output_path)))


def ConvertSdk():
  sdk_root = sys.argv[1]
  print(("Processing {}".format(sdk_root)))
  GenerateMeson(sdk_root)


if __name__ == '__main__':
  sys.exit(ConvertSdk())
